// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6BZKYE__GbisG-qIJUZ_OmpjwGUzthXw',
    appId: '1:1030334725553:web:fea2ffb0f79bd8c5d85190',
    messagingSenderId: '1030334725553',
    projectId: 'zadiag-22482',
    authDomain: 'zadiag-22482.firebaseapp.com',
    storageBucket: 'zadiag-22482.firebasestorage.app',
    measurementId: 'G-8ZYB3WJM54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4bB0Hnfeq7J04xqxVFL9L2FAdY-kVA9k',
    appId: '1:1030334725553:android:03f0d7e27896e26ad85190',
    messagingSenderId: '1030334725553',
    projectId: 'zadiag-22482',
    storageBucket: 'zadiag-22482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9oRNEBNOXbU_2PMrSRcVKChrvagWGyD8',
    appId: '1:1030334725553:ios:75302b2144055441d85190',
    messagingSenderId: '1030334725553',
    projectId: 'zadiag-22482',
    storageBucket: 'zadiag-22482.firebasestorage.app',
    iosBundleId: 'com.dime.zadiag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9oRNEBNOXbU_2PMrSRcVKChrvagWGyD8',
    appId: '1:1030334725553:ios:75302b2144055441d85190',
    messagingSenderId: '1030334725553',
    projectId: 'zadiag-22482',
    storageBucket: 'zadiag-22482.firebasestorage.app',
    iosBundleId: 'com.dime.zadiag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6BZKYE__GbisG-qIJUZ_OmpjwGUzthXw',
    appId: '1:1030334725553:web:9957f1ec8b692bffd85190',
    messagingSenderId: '1030334725553',
    projectId: 'zadiag-22482',
    authDomain: 'zadiag-22482.firebaseapp.com',
    storageBucket: 'zadiag-22482.firebasestorage.app',
    measurementId: 'G-0EVJBP5CTD',
  );
}
